import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'sw';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Cart translations
    cartTitle: 'Your Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptyDescription: 'Add items to get started!',
    cartTotal: 'Total',
    checkoutButton: 'Proceed to Checkout',
    removeFromCart: 'Remove from cart',
    cartItems: 'items',
    
    // Header translations
    home: 'Home',
    products: 'Products',
    admin: 'Admin',
    profile: 'Profile',
    login: 'Login',
    cart: 'Cart',
    searchPlaceholder: 'Search for products...',
    recentSearches: 'Recent Searches',
    popularSearches: 'Popular Searches',
    noSuggestions: 'No suggestions found',
    clearFilters: 'Clear all filters',
    
    // PWA Navigation translations
    search: 'Search',
    recent: 'Recent',
    settings: 'Settings',
    homeLabel: 'Home',
    productsLabel: 'Products',
    cartLabel: 'Cart',
    profileLabel: 'Profile',
    
    // HomePage translations
    freshGroceries: 'Fresh Groceries',
    deliveredFast: 'Delivered Fast',
    heroDescription: 'Get farm-fresh vegetables, fruits, and groceries delivered to your doorstep in Dar es Salaam. Quick, reliable, and always fresh.',
    shopNow: 'Shop Now',
    downloadApp: 'Download App',
    fastDelivery: 'Fast Delivery',
    farmFresh: 'Farm Fresh',
    thirtyMinDelivery: '30min Delivery',
    qualityGuaranteed: 'Quality Guaranteed',
    featuredProducts: 'Featured Products',
    handpickedItems: 'Handpicked fresh items just for you',
    loadingProducts: 'Loading products...',
    howItWorks: 'How It Works',
    howItWorksDescription: 'Getting fresh groceries delivered has never been easier. Just 3 simple steps to freshness.',
    browseSelect: 'Browse & Select',
    browseSelectDescription: 'Choose from our wide selection of fresh vegetables, fruits, and groceries. Filter by category or search for specific items.',
    scheduleDelivery: 'Schedule Delivery',
    scheduleDeliveryDescription: 'Pick your preferred delivery time slot. We offer same-day delivery across Dar es Salaam from 8 AM to 8 PM.',
    receiveFresh: 'Receive Fresh',
    receiveFreshDescription: 'Our delivery team will bring your fresh groceries right to your doorstep. Quality guaranteed or your money back.',
    startShopping: 'Start Shopping Now',
    whyChooseFresh: 'Why Choose Fresh?',
    whyChooseFreshDescription: 'We\'re not just another grocery delivery service. Here\'s what makes us different.',
    farmToDoor: 'Farm-to-Door Freshness',
    farmToDoorDescription: 'Direct partnerships with local farmers ensure you get the freshest produce, harvested within 24 hours of delivery.',
    lightningFast: 'Lightning Fast Delivery',
    lightningFastDescription: 'Average delivery time of just 30 minutes across Dar es Salaam. Same-day delivery available for all orders.',
    qualityGuarantee: 'Quality Guarantee',
    qualityGuaranteeDescription: 'Every item is hand-picked and quality-checked. Not satisfied? We\'ll replace it for free or give you a full refund.',
    trustedByThousands: 'Trusted by Thousands',
    trustedByThousandsDescription: 'Join over 10,000 satisfied customers who trust Fresh for their daily grocery needs across Tanzania.',
    customerRating: 'Customer Rating',
    onTimeDelivery: 'On-time Delivery',
    whatCustomersSay: 'What Our Customers Say',
    whatCustomersSayDescription: 'Don\'t just take our word for it. Here\'s what real customers have to say about Fresh.',
    customerSay1: 'Fresh has been a game-changer for our family. The vegetables are always crisp and the fruits are perfectly ripe. Delivery is so reliable - they\'ve never been late!',
    customerSay2: 'As a restaurant owner, quality is everything. Fresh consistently delivers the highest quality produce. Their farm partnerships really show in the freshness.',
    customerSay3: 'Love that I can get organic produce delivered so quickly. The app is super easy to use and the customer service is excellent. Highly recommend!',
    happyCustomers: 'Happy Customers',
    ordersDelivered: 'Orders Delivered',
    averageRating: 'Average Rating',
    customerRetention: 'Customer Retention',
    readyToGetFresh: 'Ready to Get Fresh?',
    readyToGetFreshDescription: 'Join thousands of satisfied customers who trust Fresh for their daily grocery needs. Fast delivery, guaranteed quality, unbeatable prices.',
    startShoppingCTA: 'Start Shopping',
    learnMore: 'Learn More',
    
    // ProductsPage translations
    allProducts: 'All Products',
    discoverGroceries: 'Discover fresh groceries delivered to your doorstep in Dar es Salaam',
    showingProducts: 'Showing',
    ofProducts: 'of',
    productsCount: 'products',
    inCategory: 'in',
    noProductsFound: 'No products found',
    noProductsFoundDescription: 'Try adjusting your search or filters to find what you\'re looking for.',
    browseMore: 'Browse More',
    
    // Download App Dialog translations
    installWebApp: 'Install Fresh Web App',
    webAppDescription: 'Install our web app for the best shopping experience on your device.',
    howToInstall: 'How to Install:',
    installStep1: 'Click the share button in your browser',
    installStep2: 'Select "Add to Home Screen"',
    installStep3: 'Open the app from your home screen',
    worksOnAllDevices: 'Works on all devices!',
    nativeAppsComing: 'Native apps coming soon!',
    nativeAppsDescription: 'We\'re working on dedicated mobile apps for iOS and Android.',
    
    // PWA Install Banner translations

    
    // OrderTracker translations
    issue: 'Issue',
    pleaseSelectRatingBeforeSubmittingFeedback: 'Please select a rating before submitting feedback.',
    thankYou: 'Thank You!',
    feedbackReceivedThankYou: 'Your feedback has been received. Thank you for your review!',
    technicalIssuePleaseTryAgain: 'There is a technical issue. Please try again.',
    loading: 'Loading...',
    orderTracking: 'Order Tracking',
    orderProgress: 'Order Progress',
    orderNumberLabel: 'Order Number',
    total: 'Total',
    date: 'Date',
    time: 'Time',
    orderTimeline: 'Order Timeline',
    orderReceived: 'Order Received',
    orderConfirmed: 'Order Confirmed',
    preparing: 'Preparing',
    readyForPickup: 'Ready for Pickup',
    outForDelivery: 'Out for Delivery',
    delivered: 'Delivered',
    liveTracking: 'Live Tracking',
    deliveryInformation: 'Delivery Information',
    serviceRating: 'Service Rating',
    youRated: 'You rated',
    rateService: 'Rate Service',
    rateDeliveryService: 'Rate Delivery Service',
    rating1to5Stars: 'Rating (1-5 stars)',
    feedbackOptional: 'Feedback (optional)',
    tellUsAboutService: 'Tell us about the service...',
    submitRating: 'Submit Rating',
    
    // UserProfile translations
    profileUpdated: 'Profile updated!',
    profileSavedSuccessfully: 'Your profile has been saved successfully.',
    failedToSaveProfile: 'Failed to save profile. Please try again.',
    loggedOut: 'Logged out',
    successfullyLoggedOut: 'You\'ve been successfully logged out.',
    failedToLogout: 'Failed to logout. Please try again.',
    freshUser: 'Fresh User',
    userProfile: 'Profile',
    orders: 'Orders',
    favorites: 'Favorites',
    loadingProfile: 'Loading profile...',
    email: 'Email',
    deliveryAddress: 'Delivery Address',
    enterDeliveryAddress: 'Enter your address in Dar es Salaam',
    saving: 'Saving...',
    saveProfile: 'Save Profile',
    memberSince: 'Member since',
    lastLogin: 'Last login',
    loadingOrders: 'Loading orders...',
    noOrdersYet: 'No orders yet',
    orderHistoryWillAppearHere: 'Your order history will appear here',
    startShoppingButton: 'Start Shopping',
    loadingFavorites: 'Loading favorites...',
    noFavoritesYet: 'No favorites yet',
    productsYouFavoriteWillAppearHere: 'Products you favorite will appear here',
    browseProducts: 'Browse Products',
    logout: 'Logout',
    
    // CheckoutPage translations
    emptyCart: 'Empty Cart',
    addItemsBeforeCheckout: 'Please add items before checkout',
    returnToShop: 'Return to Shop',
    
    // Login/Signup translations
    emailPhoneRequired: 'Email/Phone Required',
    enterEmailOrPhone: 'Please enter your email address or phone number.',
    passwordRequired: 'Password Required',
    enterPassword: 'Please enter your password.',
    verificationCodeSent: 'Verification Code Sent!',
    checkEmailSMSForCode: 'Check your email/SMS for the verification code.',
    loginFailed: 'Login Failed',
    invalidCredentials: 'Invalid credentials. Please try again.',
    nameRequired: 'Name Required',
    enterFullName: 'Please enter your full name.',
    emailRequired: 'Email Required',
    enterEmailAddress: 'Please enter your email address.',
    phoneRequired: 'Phone Required',
    enterPhoneNumber: 'Please enter your phone number.',
    passwordsDontMatch: 'Passwords Don\'t Match',
    passwordsMustMatch: 'Please make sure both passwords match.',
    passwordTooShort: 'Password Too Short',
    passwordMinLength: 'Password must be at least 6 characters long.',
    accountCreated: 'Account Created!',
    verifyEmailToCompleteRegistration: 'Please verify your email to complete registration.',
    signupFailed: 'Signup Failed',
    failedToCreateAccount: 'Failed to create account. Please try again.',
    codeRequired: 'Code Required',
    enterVerificationCode: 'Please enter the verification code.',
    invalidCode: 'Invalid Code',
    incorrectVerificationCode: 'The verification code is incorrect. Please try again.',
    welcomeToFresh: 'Welcome to Fresh!',
    successfullyLoggedIn: 'You\'ve successfully logged in.',
    accountCreatedSuccessfully: 'Your account has been created successfully!',
    welcomeBack: 'Welcome Back',
    joinFreshToday: 'Join Fresh Today',
    signInToContinueShopping: 'Sign in to continue shopping for fresh groceries',
    createAccountToStartShopping: 'Create your account and start shopping for fresh groceries',
    verificationCodeSentTo: 'We sent a 6-digit code to',
    forTestingUseCode: 'For testing, you can use',
    emailOrPhoneNumber: 'Email or Phone Number',
    emailOrPhonePlaceholder: 'your@email.com or +255 XXX XXX XXX',
    password: 'Password',
    enterYourPassword: 'Enter your password',
    signingIn: 'Signing In...',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Nambari ya Simu',
    phoneNumberPlaceholder: '+255 7XX XXX XXX or +255 6XX XXX XXX',
    phoneNumberPlaceholderSw: '+255 7XX XXX XXX',
    createPassword: 'Create a password',
    confirmPassword: 'Confirm Password',
    confirmYourPassword: 'Confirm your password',
    creatingAccount: 'Creating Account...',
    createAccount: 'Create Account',
    verificationCodeLogin: 'Verification Code',
    enter6DigitCode: 'Enter 6-digit code',
    verifying: 'Verifying...',
    verifyAndLogin: 'Verify & Login',
    backToEmail: 'Back to Email',
    byContinuingYouAgree: 'By continuing, you agree to Fresh\'s terms of service and privacy policy.',
    
    // Customer Support translations
    customerSupport: 'Customer Support',
    contactUs: 'Contact Us',
    myTickets: 'My Tickets',
    faq: 'FAQ',
    callUs: 'Call Us',
    available247: 'Available 24/7',
    responseWithin2Hours: 'Response within 2 hours',
    workingHours: 'Working Hours',
    morningToEvening: 'Morning 6 - Evening 10',
    everyday: 'Everyday',
    createSupportTicket: 'Create Support Ticket',
    priority: 'Priority',
    orderNumberOptional: 'Order Number (optional)',
    ifOrderIssue: 'If order related issue',
    issueSubject: 'Issue Subject',
    brieflyDescribeIssue: 'Briefly describe the issue',
    detailedDescription: 'Detailed Description',
    describeIssueInDetail: 'Describe your issue in detail so we can assist you properly...',
    sendTicket: 'Send Ticket',
    insufficientInfo: 'Insufficient Information',
    pleaseFillRequiredFields: 'Please fill all required fields.',
    ticketCreated: 'Ticket Created',
    ticketReceived: 'Your ticket has been received. We will contact you shortly.',
    ticketOpen: 'Open',
    ticketInProgress: 'In Progress',
    ticketResolved: 'Resolved',
    noSupportTickets: 'No support tickets',
    yourSupportTicketsWillAppearHere: 'Your support tickets will appear here',
    created: 'Created',
    order: 'Order',
    faq1Question: 'Can I modify my order after checkout?',
    faq1Answer: 'You can modify your order within 5 minutes after placing it. After that, the order is already in preparation.',
    faq2Question: 'What payment methods do you accept?',
    faq2Answer: 'We accept cash on delivery and Mobile Money (M-Pesa, Tigo Pesa, Airtel Money).',
    faq3Question: 'How long is the delivery time?',
    faq3Answer: 'Delivery time is 2-4 hours depending on your location and demand level. You will receive progress updates.',
    faq4Question: 'Is there a delivery fee?',
    faq4Answer: 'There is no delivery fee for orders of TZS 50,000 and above. For orders below that, the fee is TZS 3,000.',
    faq5Question: 'What can I do if I am not satisfied with the products?',
    faq5Answer: 'If you are not satisfied, contact us within 24 hours. We will refund you or replace the products according to the situation.',
    
    // Category translations
    categories: 'Categories',
    categoryVegetables: 'Fresh Vegetables',
    categoryFruits: 'Fresh Fruits',
    categoryHerbs: 'Herbs & Spices',
    categoryDairy: 'Dairy & Eggs',
    categoryGrains: 'Grains & Cereals',
    categoryMeat: 'Fresh Meat',
    categoryBeverages: 'Beverages',
    categorySnacks: 'Snacks',
    categoryHousehold: 'Household',
    categoryOther: 'Other',
    
    // ProductCard translations
    addedToCart: 'Added to cart!',
    addedToCartDescription: 'has been added to your cart.',
    loginRequired: 'Login Required',
    loginToAddToFavorites: 'Please log in to save favorites.',
    removedFromFavorites: 'Removed from favorites',
    removedFromFavoritesDescription: 'has been removed from your favorites.',
    addedToFavorites: 'Added to favorites!',
    addedToFavoritesDescription: 'has been added to your favorites.',
    error: 'Error',
    failedToUpdateFavorites: 'Failed to update favorites. Please try again.',
    
    // General translations
    addToCart: 'Add to Cart',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    pcs: 'pcs',
    kg: 'kg',
    grams: 'grams',
    
    // Admin translations
    accessDenied: 'Access Denied',
    needAdminPrivileges: 'You need admin privileges to migrate data.',
    migrationComplete: 'Migration Complete',
    productsMigratedSuccessfully: 'Products have been migrated to the database successfully!',
    migrationFailed: 'Migration Failed',
    failedToMigrateProducts: 'Failed to migrate products. Please try again.',
    verified: 'Verified',
    
    // AdminNotificationCenter translations
    lowStockAlert: 'Low Stock Alert',
    productsRunningLow: 'Products are running low on stock',
    viewProducts: 'View Products',
    navigatingToProducts: 'Navigating to Products',
    showingLowStockProducts: 'Showing low stock products',
    newOrders: 'New Orders',
    newOrdersReceived: 'New orders received in the last hour',
    viewOrders: 'View Orders',
    navigatingToOrders: 'Navigating to Orders',
    showingRecentOrders: 'Showing recent orders',
    systemUpdate: 'System Update',
    adminDashboardUpdated: 'Admin dashboard successfully updated',
    criticalStockLevels: 'Critical Stock Levels',
    multipleProductsBelowThreshold: 'Multiple products below minimum threshold',
    pendingOrders: 'Pending Orders',
    ordersWaitingForConfirmation: 'Orders waiting for confirmation',
    ago: 'ago',
    justNow: 'Just now',
    adminNotifications: 'Admin Notifications',
    criticalAlerts: 'Critical Alerts',
    items: 'items',
    recentActivity: 'Recent Activity',
    noNotifications: 'No notifications',
    
    // OrderConfirmationPage translations
    orderPending: 'Pending Confirmation',
    orderPendingDescription: 'Your order has been received and is awaiting confirmation',
    orderConfirmedStatus: 'Confirmed',
    orderConfirmedDescription: 'Your order has been confirmed and is being prepared',
    orderPreparing: 'Preparing',
    orderPreparingDescription: 'Your items are being prepared for delivery',
    orderOutForDelivery: 'Out for Delivery',
    orderOutForDeliveryDescription: 'Your items are on their way to you',
    orderDelivered: 'Delivered',
    orderDeliveredDescription: 'Your items have been successfully delivered',
    orderCancelled: 'Cancelled',
    orderCancelledDescription: 'This order has been cancelled',
    loadingOrderInfo: 'Loading order information...',
    orderNotFound: 'Order Not Found',
    congratulations: 'Congratulations!',
    orderCompleted: 'Your order is complete and has been sent',
    orderNumber: 'Order Number',
    orderConfirmationAddress: 'Address',
    orderConfirmationPhone: 'Phone',
    phone: 'Phone',
    dateAndTime: 'Date and Time',
    additionalNotes: 'Additional Notes',
    orderedItems: 'Ordered Items',
    productTotal: 'Product Total',
    deliveryFee: 'Delivery Fee',
    paymentInformation: 'Payment Information',
    cashOnDelivery: 'Cash on Delivery',
    mobileMoney: 'Mobile Money',
    payOnDelivery: 'Pay in cash upon delivery',
    paymentMessage: 'You will receive a payment message on your phone',
    continueShopping: 'Continue Shopping',
    trackOrder: 'Track Order',
    viewOrderHistory: 'View Order History',
    needHelp: 'Need Help?',
    contactUsForQuestions: 'Contact us for any questions about your order',
    contactEmail: 'Email',
    
    // DeliveryPage translations
    orderNotFoundOrNoPermission: 'Order not found or you don\'t have permission to view it.',
    failedToLoadOrderInfo: 'Failed to load order information. Please try again.',
    back: 'Back',
    orderDetails: 'Order Details',
    customer: 'Customer',
    deliveryTime: 'Time',
    status: 'Status',
    deliveryNotes: 'Notes',
    deliveryPersonSystem: 'Delivery Person System',
    notAssignedToDelivery: 'Not Assigned to Delivery',
    orderNotAssignedYet: 'Your order has not been assigned to a delivery person yet. You will receive notification when a delivery person is assigned.',
    needHelpContact: 'Need help? Contact us at',
    
    // ProductPage translations
    productNotFound: 'Product Not Found',
    returnToHome: 'Return to Home',
    backToProducts: 'Back to Products',
    reviews: 'reviews',
    quantity: 'Quantity',
    description: 'Description',
    nutrition: 'Nutrition',
    aboutThisProduct: 'About this product',
    freshAndHighQuality: 'Fresh and high-quality',
    sourcedDirectly: 'sourced directly from local farms. Perfect for your daily cooking needs with guaranteed freshness and taste.',
    category: 'Category',
    unit: 'Unit',
    origin: 'Origin',
    localFarms: 'Local Farms, Tanzania',
    freshness: 'Freshness',
    harvestedDaily: 'Harvested Daily',
    nutritionalInformation: 'Nutritional Information',
    per100gServing: 'Per 100g serving',
    calories: 'Calories',
    protein: 'Protein',
    carbohydrates: 'Carbohydrates',
    fiber: 'Fiber',
    fat: 'Fat',
    vitaminC: 'Vitamin C',
    customerReviews: 'Customer Reviews',
    writeReview: 'Write Review',
    daysAgo: 'days ago',
    greatQuality: 'Great quality and very fresh. Delivered quickly and packaging was excellent.',
    relatedProducts: 'Related Products',
    linkCopied: 'Link copied!',
    productLinkCopied: 'Product link copied to clipboard.',
    
    // NotFoundPage translations
    pageNotFoundTitle: 'Page Not Found',
    pageNotFoundDescription: 'The page you are looking for does not exist.',
    pageNotFoundMessage: 'Sorry, we couldn\'t find the page you\'re looking for.',
    pageNotFoundExplanation: 'The page may have been moved or deleted.',
    goBack: 'Go Back',
    returnHome: 'Return Home',
    
    // ClickPesaCheckout translations
    deliveryDetails: 'Delivery Details',
    enterDeliveryInformation: 'Enter your delivery information',
    paymentMethod: 'Payment Method',
    choosePaymentMethod: 'Choose your preferred payment method',
    reviewConfirm: 'Review & Confirm',
    reviewOrderBeforePayment: 'Review your order before payment',
    payment: 'Payment',
    completePayment: 'Complete your payment',
    missingInformation: 'Missing Information',
    streetAddress: 'Street Address',
    enterFullAddress: 'Enter your full address...',
    ward: 'Ward',
    'e.g., Mikocheni, Masaki': 'e.g., Mikocheni, Masaki',
    district: 'District',
    deliveryDate: 'Delivery Date',
    timeSlot: 'Time Slot',
    deliveryInstructions: 'Delivery Instructions',
    optional: 'Optional',
    specialInstructionsForDelivery: 'Special instructions for delivery...',
    tigoPesa: 'Tigo Pesa',
    payWithTigoPesa: 'Pay with Tigo Pesa (Instant)',
    noAdditionalFees: 'No additional fees',
    airtelMoney: 'Airtel Money',
    payWithAirtelMoney: 'Pay with Airtel Money (Instant)',
    mpesa: 'M-Pesa',
    payWithMpesa: 'Pay with Vodacom M-Pesa',
    contactSupportToActivate: 'Contact support to activate',
    creditDebitCard: 'Credit/Debit Card',
    visaMastercard: 'Visa, MasterCard (0-2 business days)',
    completeKycToEnable: 'Complete KYC to enable',
    payWhenReceiveOrder: 'Pay when you receive your order',
    deliveryFeeTzs: 'TZS 2,000 fee',
    paymentToBeCollectedOnDelivery: 'Payment to be collected on delivery',
    orderPlacedSuccessfully: 'Order Placed Successfully!',
    yourOrderHasBeenPlaced: 'Your order has been placed. Pay when delivered.',
    orderFailed: 'Order Failed',
    failedToCreateOrder: 'Failed to create order. Please try again.',
    redirectedToPayment: 'Redirected to Payment',
    completePaymentInNewTab: 'Complete your payment in the new tab. We\'ll redirect you to order tracking.',
    processing: 'Processing...',
    placeOrder: 'Place Order',
    securedByClickPesa: 'Secured by ClickPesa',
    youWillBeRedirectedTo: 'You\'ll be redirected to',
    toCompletePayment: 'to complete your payment securely.',
    orderSummary: 'Order Summary',
    qty: 'Qty',
    subtotal: 'Subtotal',
    vat: 'Tax (VAT)',
    free: 'FREE',
    address: 'Address',
    instructions: 'Instructions',
    orderTotal: 'Order Total',
    delivery: 'Delivery',
    previous: 'Previous',
    continue: 'Continue',
    orderCreatedSuccessfully: 'Order Created Successfully!',
    paymentAmount: 'Payment Amount',
    continueToClickPesa: 'Continue to ClickPesa',
    youWillBeRedirectedToClickPesa: 'You will be redirected to ClickPesa\'s secure payment page',
    checkout: 'Checkout',
    completeYourOrderSecurely: 'Complete your order securely',
    
    // New ClickPesa translations
    paymentInitiated: 'Payment Initiated',
    checkYourPhoneForPaymentPrompt: 'Check your phone for a payment prompt. You will receive a USSD request to complete your payment.',
    continueToOrderConfirmation: 'Continue to Order Confirmation',
    youWillReceiveUSSDPrompt: 'You will receive a USSD prompt on your phone to complete the payment.',
    
    // Download App Dialog translations,
    
    // Download App Dialog translations,
    
    // PWA Install Banner translations

    
    // OrderManagement translations
    orderManagement: 'Order Management',
    refresh: 'Refresh',
    noStatusOrders: 'No {status} orders',
    amount: 'Amount',
    viewDetails: 'View Details',
    customerPhone: 'Customer Phone',
    at: 'at',
    orderItems: 'Order Items',
    confirmOrder: 'Confirm Order',
    startPreparing: 'Start Preparing',
    assignDelivery: 'Assign Delivery',
    markDelivered: 'Mark Delivered',
    success: 'Success',
    orderStatusUpdatedTo: 'Order status updated to',
    failedToUpdateOrderStatus: 'Failed to update order status. Please try again.',
    deliveryPersonAssigned: 'Delivery person assigned successfully',
    failedToAssignDeliveryPerson: 'Failed to assign delivery person. Please try again.',
    failedToLoadOrders: 'Failed to load orders. Please try again.',
    
    // LiveDeliveryTracker translations
    failedToLoadDeliveryData: 'Failed to load delivery data. Please try again.',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    assigned: 'Assigned',
    pickedUp: 'Picked Up',
    inTransit: 'In Transit',
    deliveredStatus: 'Delivered',
    failed: 'Failed',
    loadingDeliveryInfo: 'Loading delivery information...',
    noDeliveryInfo: 'No delivery information',
    orderNotAssignedToDelivery: 'Order not assigned to delivery yet',
    estimatedArrival: 'Estimated Arrival',
    distanceRemaining: 'Distance Remaining',
    currentLocation: 'Current Location',
    updated: 'Updated',
    speed: 'Speed',
    notes: 'Notes',
    openInGoogleMaps: 'Open in Google Maps',
    locationHistory: 'Location History',
    updates: 'updates',
    refreshingEvery: 'Refreshing every',
    seconds: 'seconds',
    
    // Demo Payment Page translations
    noExtraFees: 'No Extra Fees',
    oneToTwoMinutes: '1-2 Minutes',
    instant: 'Instant',
    cardFee: '2.5% Fee',
    invalidPaymentLink: 'Invalid Payment Link',
    requiredPaymentParametersMissing: 'Required payment parameters are missing',
    phoneNumberRequired: 'Phone Number Required',
    enterPhoneNumberToContinue: 'Please enter your phone number to continue',
    paymentReceivedDemo: 'Payment Received (demo)',
    paymentProcessedSuccessfully: 'Payment processed successfully',
    somethingWentWrong: 'Something went wrong',
    securePayment: 'Secure Payment',
    demoMode: 'Demo Mode',
    simulatedPaymentExperience: 'This is a simulated payment experience for demonstration purposes',
    selectPaymentMethod: 'Select Payment Method',
    continueWith: 'Continue with',
    enterYour: 'Enter your',
    number: 'number',
    cardPaymentDemo: 'Card payment is in demo mode',
    pay: 'Pay',
    paymentSuccessful: 'Payment Successful',
    yourPaymentOf: 'Your payment of',
    hasBeenProcessedSuccessfully: 'has been processed successfully',
    paymentReference: 'Payment Reference',
    method: 'Method',
    
    // Admin Debug Component translations
    welcome: 'Welcome',
    adminNotFound: 'Admin Not Found',
    creatingInitialAdmin: 'Creating initial admin...',
    failedToLoginAsAdmin: 'Failed to login as admin. Check console for details.',
    adminCreatedLoggedIn: 'Admin Created and Logged In',
    initialAdminCreated: 'Initial admin user created successfully!',
    failedToCreateAdmin: 'Failed to Create Admin',
    couldNotCreateInitialAdmin: 'Could not create initial admin user.',
    adminPermissionsTest: '=== Admin Permissions Test ===',
    allowed: 'Allowed',
    denied: 'Denied',
    permissionTestComplete: 'Permission Test Complete',
    checkConsoleForResults: 'Check console for detailed results.',
    adminDebugPanel: 'Admin Debug Panel',
    adminStatus: 'Admin Status',
    adminLoggedIn: 'Admin Logged In',
    notAdmin: 'Not Admin',
    adminEmail: 'Admin Email',
    loggingIn: 'Logging in...',
    loginAsAdmin: 'Login as Admin',
    dashboard: 'Dashboard',
    testPerms: 'Test Perms',
    logoutAdmin: 'Logout Admin',
    defaultAdmin: 'Default Admin',
    role: 'Role',
    fullAccess: 'full access',
    adminUsesSeparateAuth: 'Admin uses separate authentication from regular users',
    
    // ClickPesa Test Component translations
    clickPesaHealthCheck: 'ClickPesa Health Check',
    testCustomer: 'Test Customer',
    clickPesaIntegrationTestPayment: 'ClickPesa Integration Test Payment',
    clickPesaIntegrationTestSuccessful: 'ClickPesa integration test successful! Payment URL created.',
    clickPesaTestResult: 'ClickPesa Test Result',
    clickPesaTestFailed: 'ClickPesa Test Failed',
    unknownErrorOccurred: 'Unknown error occurred',
    clickPesaIntegrationTest: 'ClickPesa Integration Test',
    testYourClickPesaCredentials: 'Test your ClickPesa credentials and payment gateway integration',
    configurationStatus: 'Configuration Status',
    apiKey: 'API Key',
    merchantId: 'Merchant ID',
    payBill: 'Pay Bill',
    set: 'Set',
    missing: 'Missing',
    mode: 'Mode',
    demo: 'Demo',
    production: 'Production',
    testingClickPesaConnection: 'Testing ClickPesa connection...',
    testClickPesaIntegration: 'Test ClickPesa Integration',
    testSuccessful: 'Test Successful!',
    testFailed: 'Test Failed',
    openTestPaymentPage: 'Open Test Payment Page',
    toCompleteSetup: 'To complete setup:',
    updateYourEnvFile: 'Update your .env file with real ClickPesa credentials',
    setDemoModeToFalse: 'Set VITE_CLICKPESA_DEMO_MODE=false for production',
    restartDevelopmentServer: 'Restart your development server',
    clickTestClickPesaIntegration: 'Click "Test ClickPesa Integration" to verify',
    contactRequired: 'Contact Required',
    kycRequired: 'KYC Required',
    
    // Admin Login Page translations
    adminAccountCreated: 'Admin Account Created',
    adminAccountCreatedDescription: 'Admin account created successfully.',
    adminLoginSuccessful: 'Admin Login Successful',
    adminWelcomeBack: 'Admin Welcome Back',
    adminLoginFailed: 'Admin Login Failed',
    adminInvalidCredentials: 'Invalid credentials. Please try again.',
    backToFresh: 'Back to Fresh',
    adminPortal: 'Admin Portal',
    signInToAccessAdminDashboard: 'Sign in to access admin dashboard',
    authorizedPersonnelOnly: 'Authorized Personnel Only',
    restrictedAreaWarning: 'This area is restricted to admin users only. Unauthorized access attempts are logged and monitored.',
    adminEmailAddress: 'Admin Email Address',
    adminPassword: 'Admin Password',
    adminEnterYourPassword: 'Enter your admin password',
    adminSigningIn: 'Admin Signing In...',
    adminSignIn: 'Admin Sign In',
    adminDemoCredentials: 'Demo Credentials',
    adminDemoCredentialsNote: 'These are default credentials for testing',
    adminProtectedArea: 'Protected Area • Fresh Grocery Platform',
    protectedAdminArea: 'Protected admin area',
  },
  
  sw: {
    // Cart translations
    cartTitle: 'Kikapu Chako',
    cartEmpty: 'Kikapu tupu',
    cartEmptyDescription: 'Ongeza bidhaa ili kuanza kununua!',
    cartTotal: 'Jumla',
    checkoutButton: 'Maliza Ununuzi',
    removeFromCart: 'Ondoa kikapu',
    cartItems: 'bidhaa',
    
    // Header translations
    home: 'Nyumbani',
    products: 'Bidhaa',
    admin: 'Msimamizi',
    profile: 'Wasifu',
    login: 'Ingia',
    cart: 'Kikapu',
    searchPlaceholder: 'Tafuta bidhaa...',
    recentSearches: 'Utafutaji wa Hivi Karibuni',
    popularSearches: 'Utafutaji Maarufu',
    noSuggestions: 'Hakuna mapendekezo yaliyopatikana',
    clearFilters: 'Futa vichujio vyote',
    
    // PWA Navigation translations
    search: 'Tafuta',
    recent: 'Hivi Karibuni',
    settings: 'Mipangilio',
    homeLabel: 'Nyumbani',
    productsLabel: 'Bidhaa',
    cartLabel: 'Kikapu',
    profileLabel: 'Wasifu',
    
    // ProductsPage translations
    allProducts: 'Bidhaa Zote',
    discoverGroceries: 'Gundua vyakula safi vinavyowasilishwa hadi mlango wako mwa Dar es Salaam',
    showingProducts: 'Inaonyesha',
    ofProducts: 'ya',
    productsCount: 'bidhaa',
    inCategory: 'katika',
    noProductsFound: 'Hakuna bidhaa zilizopatikana',
    noProductsFoundDescription: 'Jaribu kurekebisha utafutaji au vichujio vyako ili kupata kile unachotafuta.',
    browseMore: 'Vinjari Zaidi',
    
    // Category translations
    categories: 'Kategoria',
    categoryVegetables: 'Mboga Safi',
    categoryFruits: 'Matunda Safi',
    categoryHerbs: 'Vitunguu & Viungo',
    categoryDairy: 'Maziwa & Mayai',
    categoryGrains: 'Nafaka & Mihogo',
    categoryMeat: 'Nyama Safi',
    categoryBeverages: 'Vinywaji',
    categorySnacks: 'Vyakula vya Snack',
    categoryHousehold: 'Vyombo vya Nyumbani',
    categoryOther: 'Nyingine',
    
    // HomePage translations
    freshGroceries: 'Vyakula Safi',
    deliveredFast: 'Uwasilishaji wa Haraka',
    heroDescription: 'Pata mboga safi, matunda, na vyakula vingine vilivyokusikia kutoka kwa wakulima hadi mlango wako mwa Dar es Salaam. Haraka, inaaminika, na daima safi.',
    shopNow: 'Nunua Sasa',
    downloadApp: 'Pakua Programu',
    fastDelivery: 'Uwasilishaji wa Haraka',
    farmFresh: 'Kulimwa Shambani',
    thirtyMinDelivery: 'Uwasilishaji wa Dak 30',
    qualityGuaranteed: 'Uhakiki wa Ubora',
    featuredProducts: 'Bidhaa Maarufu',
    handpickedItems: 'Bidhaa zilizochaguliwa kwa ajili yako',
    loadingProducts: 'Inapakia bidhaa...',
    howItWorks: 'Jinsi Inavyofanya Kazi',
    howItWorksDescription: 'Kupata mboga safi hajawahi kuwa rahisi zaidi. Hatua 3 rahisi tu kwa ubunifu.',
    browseSelect: 'Vinjari na Chagua',
    browseSelectDescription: 'Chagua kutoka kwa uteuzi wetu wa mboga safi, matunda, na vyakula vingine. Chuja kwa kategoria au tafuta bidhaa mahususi.',
    scheduleDelivery: 'Panga Uwasilishaji',
    scheduleDeliveryDescription: 'Chagua wakati unaopendelea wa uwasilishaji. Tunatoa uwasilishaji wa siku ile ile ile kote Dar es Salaam kutoka saa 8 AM hadi 8 PM.',
    receiveFresh: 'Pokea Bidhaa Safi',
    receiveFreshDescription: 'Timu yetu ya uwasilishaji itakuletea mboga zako safi hadi mlango wako. Ubora umehakikishwa au tutakurudishia pesa zako.',
    startShopping: 'Anza Kununua Sasa',
    whyChooseFresh: 'Kwa Nini Kuchagua Fresh?',
    whyChooseFreshDescription: 'Sisi si huduma nyingine ya uwasilishaji wa vyakula tu. Hivi ndivyo tunavyofanana.',
    farmToDoor: 'Ubunifu wa Shambani hadi Mlango',
    farmToDoorDescription: 'Ushirikiano wa moja kwa moja na wakulima wa ndani hutuhakikishia kupata bidhaa za hivi karibuni, zilizokuswa ndani ya masaa 24 ya uwasilishaji.',
    lightningFast: 'Uwasilishaji wa Haraka Sana',
    lightningFastDescription: 'Wakati wa wastani wa uwasilishaji ni dakika 30 tu kote Dar es Salaam. Uwasilishaji wa siku ile ile unapatikana kwa maagizo yote.',
    qualityGuarantee: 'Uhakiki wa Ubora',
    qualityGuaranteeDescription: 'Kila kitu kinachukuliwa kwa mkono na kuhakikishwa ubora wake. Huna furaha? Tutakubadilisha bure au kukurudishia pesa zako.',
    trustedByThousands: 'Imethibitishwa na Maelfu',
    trustedByThousandsDescription: 'Jiunge na zaidi ya wateja 10,000 waliofurahi kutumia Fresh kwa mahitaji yao ya kila siku kote Tanzania.',
    customerRating: 'Kiwango cha Wateja',
    onTimeDelivery: 'Uwasilishaji kwa Wakati',
    whatCustomersSay: 'Wateja Wetu Wanachosema',
    whatCustomersSayDescription: 'Usiweke tu maneno yetu. Hivi ndivyo wateja wa kweli wanavyosema kuhusu Fresh.',
    customerSay1: 'Fresh imekuwa mabadiliko kwa familia yetu. Mboga daima ziko safi na matunda yameiva vizuri. Uwasilishaji ni waaminifu sana - hawajawahi kuchelewa!',
    customerSay2: 'Kama mmiliki wa mkahawa, ubora ni kila kitu. Fresh daima inatoa bidhaa za ubora wa juu. Ushirikiano wao na wakulima unajionyesha katika ubunifu.',
    customerSay3: 'Ninapenda kuwa naweza kupata bidhaa za kikuu kwa haraka. Programu ni rahisi sana kutumia na huduma kwa wateja ni bora sana. Ninapendekeza sana!',
    readyToGetFresh: 'Tayari Kupata Bidhaa Safi?',
    readyToGetFreshDescription: 'Jiunge na maelfu ya wateja waliofurahi kutumia Fresh kwa mahitaji yao ya kila siku. Uwasilishaji wa haraka, ubora umehakikishwa, bei zisizoweza kushindwa.',
    startShoppingCTA: 'Anza Kununua',
    learnMore: 'Jifunze Zaidi',
    
    // HomePage statistics translations
    happyCustomers: 'Wateja Wafurahi',
    ordersDelivered: 'Maagizo Yaliyowasilishwa',
    averageRating: 'Kiwango cha Wastani',
    customerRetention: 'Uendeleaji wa Wateja',
    
    // Product names and descriptions translations
    // Vegetables
    freshTomatoes: 'Nyanya Safi',
    freshTomatoesDesc: 'Nyanya nyekundu zilizokuswa shambani, nzuri kwa kupika na saladi',
    greenSpinach: 'Sokosoko ya Kijani',
    greenSpinachDesc: 'Sokosoko yenye virutuba vingi, iliyokuswa hivi karibuni',
    redOnions: 'Vitunguu Vyekundu',
    redOnionsDesc: 'Vitunguu vitamu vyekundu, vinavyofaa kwa mahitaji yote ya kupika',
    freshCarrots: 'Karoti Safi',
    freshCarrotsDesc: 'Karoti za rangi ya machungwa, zinazojaa vitamini',
    
    // Fruits
    sweetMangoes: 'Embe Tamu',
    sweetMangoesDesc: 'Embe zilizoiva, zenye juisi kutoka kwa mashamba ya ndani',
    freshBananas: 'Ndizi Safi',
    freshBananasDesc: 'Ndizi za manjano, zilizoiva kikamili kwa kula',
    greenAvocados: 'Parachichi za Kijani',
    greenAvocadosDesc: 'Parachichi za ubora wa juu, laini na yenye virutuba',
    
    // Herbs
    freshCoriander: 'Koriana Safi',
    freshCorianderDesc: 'Majani ya koriana yenye harufu nzuri kwa viungo',
    freshMint: 'Pudina Safi',
    freshMintDesc: 'Majani ya pudina safi kwa chai na kupika',
    
    // Dairy
    freshMilk: 'Maziwa Safi',
    freshMilkDesc: 'Maziwa ya ng\'ombe safi, yanayowasilishwa kila siku',
    farmEggs: 'Mayai ya Shambani',
    farmEggsDesc: 'Mayai ya kuku wa angani kutoka kwa mashamba ya ndani',
    
    // Grains
    whiteRice: 'Wali Mweupe',
    whiteRiceDesc: 'Wali wa ubora wa juu, unaofaa kwa karamu za kila siku',
    
    // Beverages
    freshOrangeJuice: 'Juisi ya Machungwa Safi',
    freshOrangeJuiceDesc: 'Juisi iliyochanywa hivi karibuni, pasipo vifaa vya kuhifadhi',
    coconutWater: 'Maji ya Nazi',
    coconutWaterDesc: 'Maji ya nazi asili, yenye ladha nzuri na yenye afya',
    
    // Snacks
    mixedNuts: 'Nuts Zilizochanganywa',
    mixedNutsDesc: 'Nuts za ubora wa juu, zinazofaa kwa kula kwa afya',
    driedFruitsMix: 'Mchanganyiko wa Matunda Yaliyokauka',
    driedFruitsMixDesc: 'Matunda yaliyokauka asili, pasipo sukari iliyongezea',
    
    // Units
    'per kg': 'kwa kilo',
    'per bunch': 'kwa bunchi',
    'per dozen': 'kwa kumi na mbili',
    'per liter': 'kwa lita',
    'per tray (30 eggs)': 'kwa tray (mayai 30)',
    'per 5kg bag': 'kwa mfuko wa kg 5',
    'per 500ml': 'kwa ml 500',
    'per bottle': 'kwa chupa',
    'per 250g': 'kwa g 250',
    'per 200g': 'kwa g 200',
    
    // Checkout Page translations
    checkout: 'Maliza Ununuzi',
    completeYourOrderSecurely: 'Kamilisha oda yako kwa usalama',
    deliveryDetails: 'Maelezo ya Uwasilishaji',
    enterDeliveryInformation: 'Ingiza maelezo yako ya uwasilishaji',
    paymentMethod: 'Njia ya Malipo',
    choosePaymentMethod: 'Chagua njia unayopendelea ya malipo',
    reviewConfirm: 'Kagua & Thibitisha',
    reviewOrderBeforePayment: 'Kagua oda yako kabla ya malipo',
    payment: 'Malipo',
    completePayment: 'Kamilisha malipo yako',
    streetAddress: 'Anwani ya Mtaa',
    enterFullAddress: 'Ingiza anwani yako kamili...',
    ward: 'Kata',
    'e.g., Mikocheni, Masaki': 'mfano, Mikocheni, Masaki',
    district: 'Wilaya',
    deliveryDate: 'Tarehe ya Uwasilishaji',
    timeSlot: 'Muda wa Uwasilishaji',
    deliveryInstructions: 'Maelezo ya Uwasilishaji',
    optional: 'Hiari',
    specialInstructionsForDelivery: 'Maelezo maalum kwa ajili ya uwasilishaji...',
    payWithTigoPesa: 'Lipa kwa Tigo Pesa (Papo hapo)',
    noAdditionalFees: 'Hakuna ada za ziada',
    payWithAirtelMoney: 'Lipa kwa Airtel Money (Papo hapo)',
    payWithMpesa: 'Lipa kwa Vodacom M-Pesa',
    contactSupportToActivate: 'Wasiliana na usaidizi ili kuamsha',
    creditDebitCard: 'Kadi ya Mkopo/Debit',
    visaMastercard: 'Visa, MasterCard (siku 0-2 za kazi)',
    completeKycToEnable: 'Kamilisha KYC ili kuwezesha',
    cashOnDelivery: 'Lipa Wakati wa Kupokea',
    payWhenReceiveOrder: 'Lipa pesa unapopokea oda yako',
    deliveryFeeTzs: 'Ada ya TZS 2,000',
    paymentToBeCollectedOnDelivery: 'Malipo yatayakusanywa wakati wa uwasilishaji',
    missingInformation: 'Habari Zinazokosekana',
    pleaseFillRequiredFields: 'Tafadhali jaza sehemu zote zinazohitajika.',
    processing: 'Inachakata...',
    placeOrder: 'Weka Oda',
    securedByClickPesa: 'Imehifadhiwa na ClickPesa',
    previous: 'Iliyopita',
    continue: 'Endelea',
    orderSummary: 'Muhtasari wa Oda',
    qty: 'Idadi',
    subtotal: 'Jumla ndogo',
    vat: 'Kodi (VAT)',
    deliveryFee: 'Ada ya Uwasilishaji',
    deliveryInformation: 'Maelezo ya Uwasilishaji',
    free: 'BURE',
    total: 'Jumla',
    orderTotal: 'Jumla ya Oda',
    items: 'Vitu',
    orderCreatedSuccessfully: 'Oda Imeundwa Kwa Mafanikio!',
    paymentAmount: 'Kiasi cha Malipo',
    continueToClickPesa: 'Endelea na ClickPesa',
    youWillBeRedirectedToClickPesa: 'Utaelekezwa kwenye ukurasa salama wa malipo wa ClickPesa',
    youWillBeRedirectedTo: 'Utaelekezwa kwenye',
    toCompletePayment: 'kukamilisha malipo yako kwa usalama.',
    popular: 'Maarufu',
    contactRequired: 'Mawasiliano Yanahitajika',
    kycRequired: 'KYC Inahitajika',
    
    // Time slots
    timeSlot1: '08:00 - 12:00',
    timeSlot2: '12:00 - 16:00',
    timeSlot3: '16:00 - 20:00',
    
    // Time slots in Swahili
    timeSlot1Sw: '08:00 - 12:00',
    timeSlot2Sw: '12:00 - 16:00',
    timeSlot3Sw: '16:00 - 20:00',
    
    // Additional translations
    orderConfirmationAddress: 'Anwani',
    orderConfirmationPhone: 'Simu',
    phone: 'Simu',
    dateAndTime: 'Tarehe na Saa',
    phoneNumber: 'Nambari ya Simu',
    phoneNumberPlaceholderSw: '+255 7XX XXX XXX au +255 6XX XXX XXX',
    address: 'Anwani',
    instructions: 'Maelezo',
    

    
    // Login/Signup translations
    verificationCodeSentTo: 'Tumetuma msimbo wa tarakimu 6 hadi',
    forTestingUseCode: 'Kwa majaribio, unaweza kutumia',
    byContinuingYouAgree: 'Kwa kuendelea, unakubali sheria na masharti ya Fresh na sera ya faragha.',
    
    // User Profile translations
    profileUpdated: 'Profaili imesasishwa!',
    profileSavedSuccessfully: 'Profaili yako imehifadhiwa kwa mafanikio.',
    failedToSaveProfile: 'Imeshindwa kuhifadhi wasifu. Tafadhali jaribu tena.',
    loggedOut: 'Umetoka',
    successfullyLoggedOut: 'Umetoka kwa mafanikio.',
    failedToLogout: 'Imeshindwa kutoka. Tafadhali jaribu tena.',
    freshUser: 'Mtumiaji wa Fresh',
    userProfile: 'Profaili',
    orders: 'Maagizo',
    favorites: 'Vipendwa',
    loadingProfile: 'Inapakia wasifu...',
    email: 'Barua pepe',
    deliveryAddress: 'Anwani ya Uwasilishaji',
    enterDeliveryAddress: 'Ingiza anwani yako ya Dar es Salaam',
    saving: 'Inahifadhi...',
    saveProfile: 'Hifadhi Profaili',
    memberSince: 'Mwanachama tangu',
    lastLogin: 'Kuingia kwa mwisho',
    loadingOrders: 'Inapakia maagizo...',
    noOrdersYet: 'Hakuna maagizo bado',
    orderHistoryWillAppearHere: 'Historia ya maagizo yako itaonekana hapa',
    startShoppingButton: 'Anza Kununua',
    loadingFavorites: 'Inapakia vipendwa...',
    noFavoritesYet: 'Hakuna vipendwa bado',
    productsYouFavoriteWillAppearHere: 'Bidhaa unazopenda zitaonekana hapa',
    browseProducts: 'Vinjari Bidhaa',
    logout: 'Toka',
    removedFromFavorites: 'Imeondolewa kwa Vipendwa',
    removedFromFavoritesDescription: 'imeondolewa kwa vipendwa',
    enterFullName: 'Tafadhali ingiza jina lako kamili.',
    failedToRemoveFromFavorites: 'Imeshindwa kuondoa kutoka kwa vipendwa.',
  }
};

// Provider component
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on initial render
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'sw')) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const value = {
    language,
    setLanguage,
    t: (key: string) => translations[language][key] || key
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook to use the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};